kind: pipeline
name: default
image_pull_secrets:
- docker-harnesstx-docker-io
steps:
- name: docker  
  image: plugins/docker
  settings:
    username: robin.elliott@harness.io
    password: 354iGXfzzh!%!liG
    repo: harnesstx.jfrog.io/demo-apps/drone-nginx
    registry: harnesstx.jfrog.io
    tags:
      - v1.1
- name: slack
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: cicd

