kind: pipeline
name: default
image_pull_secrets:
- docker-harnesstx-docker-io
steps:
- name: docker  
  image: plugins/docker
  settings:
    username: robin.elliott@harness.io
    password: 354iGXfzzh!%!liG
    repo: harnesstx.jfrog.io/demo-apps/drone-nginx
    registry: harnesstx.jfrog.io
    tags:
      - v1.0
      
kind: pipeline
name: slack-notify
  image: plugins/slack
  webhook: https://hooks.slack.com/services/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   
  channel: cicd
  template: >      
    {{#success build.status}}
    hey all! build {{build.number}} was successful.  Good Job.
    {{ else }}
    hey all! build {{build.number}} failed.  Fix me please.
    {{/success}} 

