kind: pipeline
name: default
steps:
- name: docker  
  image: plugins/docker
  settings:
    username: robin.elliott@harness.io
    password: 354iGXfzzh!%!liG
    repo: harnesstx.jfrog.io/demo-apps/nginx
    registry: harnesstx.jfrog.io
    tags:
      - latest
image_pull_secrets:
- docker-harnesstx-docker-io
