kind: pipeline
name: default
image_pull_secrets:
- docker-harnesstx-docker-io
steps:
- name: docker  
  image: plugins/docker
  settings:
    username: robin.elliott@harness.io
    password: 354iGXfzzh!%!liG
    repo: harnesstx.jfrog.io/demo-apps/drone-nginx
    registry: harnesstx.jfrog.io
    tags:
      - v1.0
name: slack
  image: plugins/slack
  webhook: https://hooks.slack.com/services/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
  chennel: cicd
  icon_url: https://unsplash.it/256/256/?random

